//! The icons themselves: Lucide's geometry, as absolute path commands.
//!
//! Generated by `script/icons` from lucide-static 1.40.0, which is
//! ISC-licensed — see `LICENSE-ISC-lucide`. Do not edit: add an icon to
//! the script's list and run it.
//!
//! Every icon is drawn inside a 24 x 24 box with a 2-unit stroke, round
//! caps and round joins, and no fill. Arcs, shorthands and the `circle`,
//! `rect`, `line` and `polyline` elements are all resolved into moves,
//! lines and cubics here, so the rasterizer needs no SVG in it.

use super::Segment::{self, Close, Cubic, Line, Move};

/// Lucide's `check`.
pub(super) static CHECK: &[Segment] = &[Move(20.0, 6.0), Line(9.0, 17.0), Line(4.0, 12.0)];

/// Lucide's `chevron-down`.
pub(super) static CHEVRON_DOWN: &[Segment] = &[Move(6.0, 9.0), Line(12.0, 15.0), Line(18.0, 9.0)];

/// Lucide's `chevron-up`.
pub(super) static CHEVRON_UP: &[Segment] = &[Move(18.0, 15.0), Line(12.0, 9.0), Line(6.0, 15.0)];

/// Lucide's `chevron-right`.
pub(super) static CHEVRON_RIGHT: &[Segment] = &[Move(9.0, 18.0), Line(15.0, 12.0), Line(9.0, 6.0)];

/// Lucide's `copy`.
pub(super) static COPY: &[Segment] = &[
    Move(10.0, 8.0),
    Line(20.0, 8.0),
    Cubic(21.1046, 8.0, 22.0, 8.8954, 22.0, 10.0),
    Line(22.0, 20.0),
    Cubic(22.0, 21.1046, 21.1046, 22.0, 20.0, 22.0),
    Line(10.0, 22.0),
    Cubic(8.8954, 22.0, 8.0, 21.1046, 8.0, 20.0),
    Line(8.0, 10.0),
    Cubic(8.0, 8.8954, 8.8954, 8.0, 10.0, 8.0),
    Close,
    Move(4.0, 16.0),
    Cubic(2.9, 16.0, 2.0, 15.1, 2.0, 14.0),
    Line(2.0, 4.0),
    Cubic(2.0, 2.9, 2.9, 2.0, 4.0, 2.0),
    Line(14.0, 2.0),
    Cubic(15.1, 2.0, 16.0, 2.9, 16.0, 4.0),
];

/// Lucide's `ellipsis-vertical`.
pub(super) static ELLIPSIS_VERTICAL: &[Segment] = &[
    Move(13.0, 12.0),
    Cubic(13.0, 12.5523, 12.5523, 13.0, 12.0, 13.0),
    Cubic(11.4477, 13.0, 11.0, 12.5523, 11.0, 12.0),
    Cubic(11.0, 11.4477, 11.4477, 11.0, 12.0, 11.0),
    Cubic(12.5523, 11.0, 13.0, 11.4477, 13.0, 12.0),
    Close,
    Move(13.0, 5.0),
    Cubic(13.0, 5.5523, 12.5523, 6.0, 12.0, 6.0),
    Cubic(11.4477, 6.0, 11.0, 5.5523, 11.0, 5.0),
    Cubic(11.0, 4.4477, 11.4477, 4.0, 12.0, 4.0),
    Cubic(12.5523, 4.0, 13.0, 4.4477, 13.0, 5.0),
    Close,
    Move(13.0, 19.0),
    Cubic(13.0, 19.5523, 12.5523, 20.0, 12.0, 20.0),
    Cubic(11.4477, 20.0, 11.0, 19.5523, 11.0, 19.0),
    Cubic(11.0, 18.4477, 11.4477, 18.0, 12.0, 18.0),
    Cubic(12.5523, 18.0, 13.0, 18.4477, 13.0, 19.0),
    Close,
];

/// Lucide's `git-branch`.
pub(super) static GIT_BRANCH: &[Segment] = &[
    Move(15.0, 6.0),
    Cubic(10.0627, 6.0, 6.0, 10.0627, 6.0, 15.0),
    Line(6.0, 3.0),
    Move(21.0, 6.0),
    Cubic(21.0, 7.6569, 19.6569, 9.0, 18.0, 9.0),
    Cubic(16.3431, 9.0, 15.0, 7.6569, 15.0, 6.0),
    Cubic(15.0, 4.3431, 16.3431, 3.0, 18.0, 3.0),
    Cubic(19.6569, 3.0, 21.0, 4.3431, 21.0, 6.0),
    Close,
    Move(9.0, 18.0),
    Cubic(9.0, 19.6569, 7.6569, 21.0, 6.0, 21.0),
    Cubic(4.3431, 21.0, 3.0, 19.6569, 3.0, 18.0),
    Cubic(3.0, 16.3431, 4.3431, 15.0, 6.0, 15.0),
    Cubic(7.6569, 15.0, 9.0, 16.3431, 9.0, 18.0),
    Close,
];

/// Lucide's `info`.
pub(super) static INFO: &[Segment] = &[
    Move(22.0, 12.0),
    Cubic(22.0, 17.5228, 17.5228, 22.0, 12.0, 22.0),
    Cubic(6.4772, 22.0, 2.0, 17.5228, 2.0, 12.0),
    Cubic(2.0, 6.4772, 6.4772, 2.0, 12.0, 2.0),
    Cubic(17.5228, 2.0, 22.0, 6.4772, 22.0, 12.0),
    Close,
    Move(12.0, 16.0),
    Line(12.0, 12.0),
    Move(12.0, 8.0),
    Line(12.01, 8.0),
];

/// Lucide's `layout-grid`.
pub(super) static LAYOUT_GRID: &[Segment] = &[
    Move(4.0, 3.0),
    Line(9.0, 3.0),
    Cubic(9.5523, 3.0, 10.0, 3.4477, 10.0, 4.0),
    Line(10.0, 9.0),
    Cubic(10.0, 9.5523, 9.5523, 10.0, 9.0, 10.0),
    Line(4.0, 10.0),
    Cubic(3.4477, 10.0, 3.0, 9.5523, 3.0, 9.0),
    Line(3.0, 4.0),
    Cubic(3.0, 3.4477, 3.4477, 3.0, 4.0, 3.0),
    Close,
    Move(15.0, 3.0),
    Line(20.0, 3.0),
    Cubic(20.5523, 3.0, 21.0, 3.4477, 21.0, 4.0),
    Line(21.0, 9.0),
    Cubic(21.0, 9.5523, 20.5523, 10.0, 20.0, 10.0),
    Line(15.0, 10.0),
    Cubic(14.4477, 10.0, 14.0, 9.5523, 14.0, 9.0),
    Line(14.0, 4.0),
    Cubic(14.0, 3.4477, 14.4477, 3.0, 15.0, 3.0),
    Close,
    Move(15.0, 14.0),
    Line(20.0, 14.0),
    Cubic(20.5523, 14.0, 21.0, 14.4477, 21.0, 15.0),
    Line(21.0, 20.0),
    Cubic(21.0, 20.5523, 20.5523, 21.0, 20.0, 21.0),
    Line(15.0, 21.0),
    Cubic(14.4477, 21.0, 14.0, 20.5523, 14.0, 20.0),
    Line(14.0, 15.0),
    Cubic(14.0, 14.4477, 14.4477, 14.0, 15.0, 14.0),
    Close,
    Move(4.0, 14.0),
    Line(9.0, 14.0),
    Cubic(9.5523, 14.0, 10.0, 14.4477, 10.0, 15.0),
    Line(10.0, 20.0),
    Cubic(10.0, 20.5523, 9.5523, 21.0, 9.0, 21.0),
    Line(4.0, 21.0),
    Cubic(3.4477, 21.0, 3.0, 20.5523, 3.0, 20.0),
    Line(3.0, 15.0),
    Cubic(3.0, 14.4477, 3.4477, 14.0, 4.0, 14.0),
    Close,
];

/// Lucide's `menu`.
pub(super) static MENU: &[Segment] = &[
    Move(4.0, 5.0),
    Line(20.0, 5.0),
    Move(4.0, 12.0),
    Line(20.0, 12.0),
    Move(4.0, 19.0),
    Line(20.0, 19.0),
];

/// Lucide's `play`.
pub(super) static PLAY: &[Segment] = &[
    Move(5.0, 5.0),
    Cubic(4.9998, 4.2846, 5.3834, 3.6216, 6.0038, 3.2652),
    Cubic(6.6241, 2.9088, 7.3901, 2.9114, 8.008, 3.272),
    Line(20.005, 10.27),
    Cubic(20.6204, 10.6271, 21.0006, 11.2867, 21.0012, 11.9981),
    Cubic(21.0019, 12.7096, 20.6228, 13.3699, 20.008, 13.728),
    Line(8.008, 20.728),
    Cubic(7.3901, 21.0886, 6.6241, 21.0912, 6.0038, 20.7348),
    Cubic(5.3834, 20.3784, 4.9998, 19.7154, 5.0, 19.0),
    Close,
];

/// Lucide's `plus`.
pub(super) static PLUS: &[Segment] = &[
    Move(5.0, 12.0),
    Line(19.0, 12.0),
    Move(12.0, 5.0),
    Line(12.0, 19.0),
];

/// Lucide's `blocks`.
pub(super) static BLOCKS: &[Segment] = &[
    Move(10.0, 22.0),
    Line(10.0, 7.0),
    Cubic(10.0, 6.4514, 9.5486, 6.0, 9.0, 6.0),
    Line(4.0, 6.0),
    Cubic(2.9028, 6.0, 2.0, 6.9028, 2.0, 8.0),
    Line(2.0, 20.0),
    Cubic(2.0, 21.0972, 2.9028, 22.0, 4.0, 22.0),
    Line(16.0, 22.0),
    Cubic(17.0972, 22.0, 18.0, 21.0972, 18.0, 20.0),
    Line(18.0, 15.0),
    Cubic(18.0, 14.4514, 17.5486, 14.0, 17.0, 14.0),
    Line(2.0, 14.0),
    Move(15.0, 2.0),
    Line(21.0, 2.0),
    Cubic(21.5523, 2.0, 22.0, 2.4477, 22.0, 3.0),
    Line(22.0, 9.0),
    Cubic(22.0, 9.5523, 21.5523, 10.0, 21.0, 10.0),
    Line(15.0, 10.0),
    Cubic(14.4477, 10.0, 14.0, 9.5523, 14.0, 9.0),
    Line(14.0, 3.0),
    Cubic(14.0, 2.4477, 14.4477, 2.0, 15.0, 2.0),
    Close,
];

/// Lucide's `search`.
pub(super) static SEARCH: &[Segment] = &[
    Move(21.0, 21.0),
    Line(16.66, 16.66),
    Move(19.0, 11.0),
    Cubic(19.0, 15.4183, 15.4183, 19.0, 11.0, 19.0),
    Cubic(6.5817, 19.0, 3.0, 15.4183, 3.0, 11.0),
    Cubic(3.0, 6.5817, 6.5817, 3.0, 11.0, 3.0),
    Cubic(15.4183, 3.0, 19.0, 6.5817, 19.0, 11.0),
    Close,
];

/// Lucide's `settings`.
pub(super) static SETTINGS: &[Segment] = &[
    Move(9.671, 4.136),
    Cubic(9.7846, 2.941, 10.8002, 2.0174, 12.0005, 2.0174),
    Cubic(13.2008, 2.0174, 14.2164, 2.941, 14.33, 4.136),
    Cubic(14.3972, 4.8953, 14.8312, 5.5757, 15.4915, 5.9567),
    Cubic(16.1517, 6.3376, 16.958, 6.3729, 17.649, 6.051),
    Cubic(18.7396, 5.5558, 20.0433, 5.974, 20.6425, 7.0111),
    Cubic(21.2417, 8.0482, 20.9527, 9.3865, 19.979, 10.084),
    Cubic(19.3552, 10.5217, 18.983, 11.2375, 18.983, 11.9995),
    Cubic(18.983, 12.7615, 19.3552, 13.4773, 19.979, 13.915),
    Cubic(20.9527, 14.6125, 21.2417, 15.9508, 20.6425, 16.9879),
    Cubic(20.0433, 18.025, 18.7396, 18.4432, 17.649, 17.948),
    Cubic(16.958, 17.6261, 16.1517, 17.6614, 15.4915, 18.0423),
    Cubic(14.8312, 18.4233, 14.3972, 19.1037, 14.33, 19.863),
    Cubic(14.2164, 21.058, 13.2008, 21.9816, 12.0005, 21.9816),
    Cubic(10.8002, 21.9816, 9.7846, 21.058, 9.671, 19.863),
    Cubic(9.604, 19.1034, 9.1697, 18.4227, 8.5092, 18.0417),
    Cubic(7.8487, 17.6607, 7.0421, 17.6257, 6.351, 17.948),
    Cubic(5.2604, 18.4432, 3.9567, 18.025, 3.3575, 16.9879),
    Cubic(2.7583, 15.9508, 3.0473, 14.6125, 4.021, 13.915),
    Cubic(4.6448, 13.4773, 5.017, 12.7615, 5.017, 11.9995),
    Cubic(5.017, 11.2375, 4.6448, 10.5217, 4.021, 10.084),
    Cubic(3.0487, 9.3862, 2.7605, 8.0491, 3.359, 7.0127),
    Cubic(3.9575, 5.9763, 5.2596, 5.5576, 6.35, 6.051),
    Cubic(7.041, 6.3729, 7.8473, 6.3376, 8.5075, 5.9567),
    Cubic(9.1678, 5.5757, 9.6018, 4.8953, 9.669, 4.136),
    Move(15.0, 12.0),
    Cubic(15.0, 13.6569, 13.6569, 15.0, 12.0, 15.0),
    Cubic(10.3431, 15.0, 9.0, 13.6569, 9.0, 12.0),
    Cubic(9.0, 10.3431, 10.3431, 9.0, 12.0, 9.0),
    Cubic(13.6569, 9.0, 15.0, 10.3431, 15.0, 12.0),
    Close,
];

/// Lucide's `x`.
pub(super) static X: &[Segment] = &[
    Move(18.0, 6.0),
    Line(6.0, 18.0),
    Move(6.0, 6.0),
    Line(18.0, 18.0),
];

/// Lucide's `folder`.
pub(super) static FOLDER: &[Segment] = &[
    Move(20.0, 20.0),
    Cubic(21.0972, 20.0, 22.0, 19.0972, 22.0, 18.0),
    Line(22.0, 8.0),
    Cubic(22.0, 6.9028, 21.0972, 6.0, 20.0, 6.0),
    Line(12.1, 6.0),
    Cubic(11.421, 6.0067, 10.7834, 5.6671, 10.41, 5.1),
    Line(9.6, 3.9),
    Cubic(9.2304, 3.3388, 8.6019, 3.0001, 7.93, 3.0),
    Line(4.0, 3.0),
    Cubic(2.9028, 3.0, 2.0, 3.9028, 2.0, 5.0),
    Line(2.0, 18.0),
    Cubic(2.0, 19.0972, 2.9028, 20.0, 4.0, 20.0),
    Close,
];

/// Lucide's `corner-left-up`.
pub(super) static CORNER_LEFT_UP: &[Segment] = &[
    Move(14.0, 9.0),
    Line(9.0, 4.0),
    Line(4.0, 9.0),
    Move(20.0, 20.0),
    Line(13.0, 20.0),
    Cubic(10.8057, 20.0, 9.0, 18.1943, 9.0, 16.0),
    Line(9.0, 4.0),
];

/// Lucide's `keyboard`.
pub(super) static KEYBOARD: &[Segment] = &[
    Move(10.0, 8.0),
    Line(10.01, 8.0),
    Move(12.0, 12.0),
    Line(12.01, 12.0),
    Move(14.0, 8.0),
    Line(14.01, 8.0),
    Move(16.0, 12.0),
    Line(16.01, 12.0),
    Move(18.0, 8.0),
    Line(18.01, 8.0),
    Move(6.0, 8.0),
    Line(6.01, 8.0),
    Move(7.0, 16.0),
    Line(17.0, 16.0),
    Move(8.0, 12.0),
    Line(8.01, 12.0),
    Move(4.0, 4.0),
    Line(20.0, 4.0),
    Cubic(21.1046, 4.0, 22.0, 4.8954, 22.0, 6.0),
    Line(22.0, 18.0),
    Cubic(22.0, 19.1046, 21.1046, 20.0, 20.0, 20.0),
    Line(4.0, 20.0),
    Cubic(2.8954, 20.0, 2.0, 19.1046, 2.0, 18.0),
    Line(2.0, 6.0),
    Cubic(2.0, 4.8954, 2.8954, 4.0, 4.0, 4.0),
    Close,
];

/// Lucide's `diff`.
pub(super) static DIFF: &[Segment] = &[
    Move(12.0, 3.0),
    Line(12.0, 17.0),
    Move(5.0, 10.0),
    Line(19.0, 10.0),
    Move(5.0, 21.0),
    Line(19.0, 21.0),
];

/// Lucide's `bell`.
pub(super) static BELL: &[Segment] = &[
    Move(10.268, 21.0),
    Cubic(10.6248, 21.618, 11.2864, 21.9999, 12.0, 21.9999),
    Cubic(12.7136, 21.9999, 13.3752, 21.618, 13.732, 21.0),
    Move(3.262, 15.326),
    Cubic(2.9956, 15.618, 2.9263, 16.0417, 3.0857, 16.4034),
    Cubic(3.2452, 16.7651, 3.6047, 16.9997, 4.0, 17.0),
    Line(20.0, 17.0),
    Cubic(20.3952, 17.0001, 20.755, 16.766, 20.9149, 16.4045),
    Cubic(21.0748, 16.0431, 21.006, 15.6193, 20.74, 15.327),
    Cubic(19.41, 13.956, 18.0, 12.499, 18.0, 8.0),
    Cubic(18.0, 4.7085, 15.2915, 2.0, 12.0, 2.0),
    Cubic(8.7085, 2.0, 6.0, 4.7085, 6.0, 8.0),
    Cubic(6.0, 12.499, 4.589, 13.956, 3.262, 15.326),
];

/// Lucide's `app-window`.
pub(super) static APP_WINDOW: &[Segment] = &[
    Move(4.0, 4.0),
    Line(20.0, 4.0),
    Cubic(21.1046, 4.0, 22.0, 4.8954, 22.0, 6.0),
    Line(22.0, 18.0),
    Cubic(22.0, 19.1046, 21.1046, 20.0, 20.0, 20.0),
    Line(4.0, 20.0),
    Cubic(2.8954, 20.0, 2.0, 19.1046, 2.0, 18.0),
    Line(2.0, 6.0),
    Cubic(2.0, 4.8954, 2.8954, 4.0, 4.0, 4.0),
    Close,
    Move(10.0, 4.0),
    Line(10.0, 8.0),
    Move(2.0, 8.0),
    Line(22.0, 8.0),
    Move(6.0, 4.0),
    Line(6.0, 8.0),
];

/// Lucide's `panel-top`.
pub(super) static PANEL_TOP: &[Segment] = &[
    Move(5.0, 3.0),
    Line(19.0, 3.0),
    Cubic(20.1046, 3.0, 21.0, 3.8954, 21.0, 5.0),
    Line(21.0, 19.0),
    Cubic(21.0, 20.1046, 20.1046, 21.0, 19.0, 21.0),
    Line(5.0, 21.0),
    Cubic(3.8954, 21.0, 3.0, 20.1046, 3.0, 19.0),
    Line(3.0, 5.0),
    Cubic(3.0, 3.8954, 3.8954, 3.0, 5.0, 3.0),
    Close,
    Move(3.0, 9.0),
    Line(21.0, 9.0),
];

/// Lucide's `tag`.
pub(super) static TAG: &[Segment] = &[
    Move(12.586, 2.586),
    Cubic(12.2112, 2.211, 11.7022, 2.0001, 11.172, 2.0),
    Line(4.0, 2.0),
    Cubic(2.9028, 2.0, 2.0, 2.9028, 2.0, 4.0),
    Line(2.0, 11.172),
    Cubic(2.0001, 11.7022, 2.211, 12.2112, 2.586, 12.586),
    Line(11.29, 21.29),
    Cubic(12.2299, 22.224, 13.7701, 22.224, 14.71, 21.29),
    Line(21.29, 14.71),
    Cubic(22.224, 13.7701, 22.224, 12.2299, 21.29, 11.29),
    Close,
    Move(8.0, 7.5),
    Cubic(8.0, 7.7761, 7.7761, 8.0, 7.5, 8.0),
    Cubic(7.2239, 8.0, 7.0, 7.7761, 7.0, 7.5),
    Cubic(7.0, 7.2239, 7.2239, 7.0, 7.5, 7.0),
    Cubic(7.7761, 7.0, 8.0, 7.2239, 8.0, 7.5),
    Close,
];

/// Lucide's `rows-3`.
pub(super) static ROWS3: &[Segment] = &[
    Move(5.0, 3.0),
    Line(19.0, 3.0),
    Cubic(20.1046, 3.0, 21.0, 3.8954, 21.0, 5.0),
    Line(21.0, 19.0),
    Cubic(21.0, 20.1046, 20.1046, 21.0, 19.0, 21.0),
    Line(5.0, 21.0),
    Cubic(3.8954, 21.0, 3.0, 20.1046, 3.0, 19.0),
    Line(3.0, 5.0),
    Cubic(3.0, 3.8954, 3.8954, 3.0, 5.0, 3.0),
    Close,
    Move(21.0, 9.0),
    Line(3.0, 9.0),
    Move(21.0, 15.0),
    Line(3.0, 15.0),
];

/// Lucide's `palette`.
pub(super) static PALETTE: &[Segment] = &[
    Move(12.0, 22.0),
    Cubic(6.5142, 22.0, 2.0, 17.4858, 2.0, 12.0),
    Cubic(2.0, 6.5142, 6.5142, 2.0, 12.0, 2.0),
    Cubic(17.4858, 2.0, 22.0, 6.0627, 22.0, 11.0),
    Cubic(22.0, 13.7429, 19.7429, 16.0, 17.0, 16.0),
    Line(14.75, 16.0),
    Cubic(14.0882, 16.0, 13.4807, 16.3754, 13.1848, 16.9674),
    Cubic(12.8888, 17.5593, 12.9529, 18.2705, 13.35, 18.8),
    Line(13.65, 19.2),
    Cubic(14.0471, 19.7295, 14.1112, 20.4407, 13.8152, 21.0326),
    Cubic(13.5193, 21.6246, 12.9118, 22.0, 12.25, 22.0),
    Close,
    Move(14.0, 6.5),
    Cubic(14.0, 6.7761, 13.7761, 7.0, 13.5, 7.0),
    Cubic(13.2239, 7.0, 13.0, 6.7761, 13.0, 6.5),
    Cubic(13.0, 6.2239, 13.2239, 6.0, 13.5, 6.0),
    Cubic(13.7761, 6.0, 14.0, 6.2239, 14.0, 6.5),
    Close,
    Move(18.0, 10.5),
    Cubic(18.0, 10.7761, 17.7761, 11.0, 17.5, 11.0),
    Cubic(17.2239, 11.0, 17.0, 10.7761, 17.0, 10.5),
    Cubic(17.0, 10.2239, 17.2239, 10.0, 17.5, 10.0),
    Cubic(17.7761, 10.0, 18.0, 10.2239, 18.0, 10.5),
    Close,
    Move(7.0, 12.5),
    Cubic(7.0, 12.7761, 6.7761, 13.0, 6.5, 13.0),
    Cubic(6.2239, 13.0, 6.0, 12.7761, 6.0, 12.5),
    Cubic(6.0, 12.2239, 6.2239, 12.0, 6.5, 12.0),
    Cubic(6.7761, 12.0, 7.0, 12.2239, 7.0, 12.5),
    Close,
    Move(9.0, 7.5),
    Cubic(9.0, 7.7761, 8.7761, 8.0, 8.5, 8.0),
    Cubic(8.2239, 8.0, 8.0, 7.7761, 8.0, 7.5),
    Cubic(8.0, 7.2239, 8.2239, 7.0, 8.5, 7.0),
    Cubic(8.7761, 7.0, 9.0, 7.2239, 9.0, 7.5),
    Close,
];

/// Lucide's `terminal`.
pub(super) static TERMINAL: &[Segment] = &[
    Move(12.0, 19.0),
    Line(20.0, 19.0),
    Move(4.0, 17.0),
    Line(10.0, 11.0),
    Line(4.0, 5.0),
];

/// Lucide's `puzzle`.
pub(super) static PUZZLE: &[Segment] = &[
    Move(15.39, 4.39),
    Cubic(15.6456, 4.6459, 16.0209, 4.7439, 16.369, 4.6457),
    Cubic(16.7171, 4.5475, 16.9858, 4.2678, 17.07, 3.916),
    Cubic(17.356, 2.7254, 18.4767, 1.9114, 19.6974, 2.0077),
    Cubic(20.918, 2.104, 21.8973, 3.0836, 21.9932, 4.3042),
    Cubic(22.089, 5.5249, 21.2747, 6.6454, 20.084, 6.931),
    Cubic(19.7322, 7.0152, 19.4525, 7.2839, 19.3543, 7.632),
    Cubic(19.2561, 7.9801, 19.3541, 8.3554, 19.61, 8.611),
    Line(21.293, 10.293),
    Cubic(21.7456, 10.7455, 22.0001, 11.36, 22.0001, 12.0),
    Cubic(22.0001, 12.64, 21.7456, 13.2545, 21.293, 13.707),
    Line(19.61, 15.39),
    Cubic(19.3544, 15.6459, 18.9791, 15.7439, 18.631, 15.6457),
    Cubic(18.2829, 15.5475, 18.0142, 15.2678, 17.93, 14.916),
    Cubic(17.644, 13.7254, 16.5233, 12.9114, 15.3026, 13.0077),
    Cubic(14.082, 13.104, 13.1027, 14.0836, 13.0068, 15.3042),
    Cubic(12.911, 16.5249, 13.7253, 17.6454, 14.916, 17.931),
    Cubic(15.2678, 18.0152, 15.5475, 18.2839, 15.6457, 18.632),
    Cubic(15.7439, 18.9801, 15.6459, 19.3554, 15.39, 19.611),
    Line(13.707, 21.293),
    Cubic(13.2545, 21.7456, 12.64, 22.0001, 12.0, 22.0001),
    Cubic(11.36, 22.0001, 10.7455, 21.7456, 10.293, 21.293),
    Line(8.61, 19.61),
    Cubic(8.3544, 19.3541, 7.9791, 19.2561, 7.631, 19.3543),
    Cubic(7.2829, 19.4525, 7.0142, 19.7322, 6.93, 20.084),
    Cubic(6.644, 21.2746, 5.5233, 22.0886, 4.3026, 21.9923),
    Cubic(3.082, 21.896, 2.1027, 20.9164, 2.0068, 19.6958),
    Cubic(1.911, 18.4751, 2.7253, 17.3546, 3.916, 17.069),
    Cubic(4.2678, 16.9848, 4.5475, 16.7161, 4.6457, 16.368),
    Cubic(4.7439, 16.0199, 4.6459, 15.6446, 4.39, 15.389),
    Line(2.707, 13.707),
    Cubic(2.2544, 13.2545, 1.9999, 12.64, 1.9999, 12.0),
    Cubic(1.9999, 11.36, 2.2544, 10.7455, 2.707, 10.293),
    Line(4.39, 8.61),
    Cubic(4.6456, 8.3541, 5.0209, 8.2561, 5.369, 8.3543),
    Cubic(5.7171, 8.4525, 5.9858, 8.7322, 6.07, 9.084),
    Cubic(6.356, 10.2746, 7.4767, 11.0886, 8.6974, 10.9923),
    Cubic(9.918, 10.896, 10.8973, 9.9164, 10.9932, 8.6958),
    Cubic(11.089, 7.4751, 10.2747, 6.3546, 9.084, 6.069),
    Cubic(8.7322, 5.9848, 8.4525, 5.7161, 8.3543, 5.368),
    Cubic(8.2561, 5.0199, 8.3541, 4.6446, 8.61, 4.389),
    Line(10.293, 2.707),
    Cubic(10.7455, 2.2544, 11.36, 1.9999, 12.0, 1.9999),
    Cubic(12.64, 1.9999, 13.2545, 2.2544, 13.707, 2.707),
    Close,
];

/// Lucide's `store`.
pub(super) static STORE: &[Segment] = &[
    Move(15.0, 21.0),
    Line(15.0, 16.0),
    Cubic(15.0, 15.4514, 14.5486, 15.0, 14.0, 15.0),
    Line(10.0, 15.0),
    Cubic(9.4514, 15.0, 9.0, 15.4514, 9.0, 16.0),
    Line(9.0, 21.0),
    Move(17.774, 10.31),
    Cubic(17.3435, 9.8979, 16.6555, 9.8979, 16.225, 10.31),
    Cubic(15.2648, 11.2258, 13.7342, 11.2258, 12.774, 10.31),
    Cubic(12.3436, 9.8985, 11.6564, 9.8985, 11.226, 10.31),
    Cubic(10.2657, 11.2265, 8.7343, 11.2265, 7.774, 10.31),
    Cubic(7.3435, 9.8979, 6.6555, 9.8979, 6.225, 10.31),
    Cubic(5.2992, 11.1935, 3.8368, 11.2307, 2.8673, 10.3954),
    Cubic(1.8978, 9.5601, 1.7182, 8.1084, 2.455, 7.062),
    Line(5.344, 2.878),
    Cubic(5.7159, 2.3293, 6.3372, 1.9999, 7.0, 2.0),
    Line(17.0, 2.0),
    Cubic(17.6609, 1.9997, 18.2806, 2.3271, 18.653, 2.873),
    Line(21.548, 7.065),
    Cubic(22.285, 8.1122, 22.1043, 9.565, 21.1332, 10.3997),
    Cubic(20.1621, 11.2344, 18.6987, 11.1949, 17.774, 10.309),
    Move(4.0, 10.95),
    Line(4.0, 19.0),
    Cubic(4.0, 20.0972, 4.9028, 21.0, 6.0, 21.0),
    Line(18.0, 21.0),
    Cubic(19.0972, 21.0, 20.0, 20.0972, 20.0, 19.0),
    Line(20.0, 10.95),
];

/// Lucide's `command`.
pub(super) static COMMAND: &[Segment] = &[
    Move(15.0, 6.0),
    Line(15.0, 18.0),
    Cubic(15.0, 19.6458, 16.3542, 21.0, 18.0, 21.0),
    Cubic(19.6458, 21.0, 21.0, 19.6458, 21.0, 18.0),
    Cubic(21.0, 16.3542, 19.6458, 15.0, 18.0, 15.0),
    Line(6.0, 15.0),
    Cubic(4.3542, 15.0, 3.0, 16.3542, 3.0, 18.0),
    Cubic(3.0, 19.6458, 4.3542, 21.0, 6.0, 21.0),
    Cubic(7.6458, 21.0, 9.0, 19.6458, 9.0, 18.0),
    Line(9.0, 6.0),
    Cubic(9.0, 4.3542, 7.6458, 3.0, 6.0, 3.0),
    Cubic(4.3542, 3.0, 3.0, 4.3542, 3.0, 6.0),
    Cubic(3.0, 7.6458, 4.3542, 9.0, 6.0, 9.0),
    Line(18.0, 9.0),
    Cubic(19.6458, 9.0, 21.0, 7.6458, 21.0, 6.0),
    Cubic(21.0, 4.3542, 19.6458, 3.0, 18.0, 3.0),
    Cubic(16.3542, 3.0, 15.0, 4.3542, 15.0, 6.0),
];

/// Every icon, its Lucide name, and its geometry.
///
/// One table rather than three `match`es, because the three answers are
/// three columns of the same row and a test walks it end to end.
pub(super) static TABLE: [(Lucide, &str, &[Segment]); ICONS] = [
    (Lucide::Check, "check", CHECK),
    (Lucide::ChevronDown, "chevron-down", CHEVRON_DOWN),
    (Lucide::ChevronUp, "chevron-up", CHEVRON_UP),
    (Lucide::ChevronRight, "chevron-right", CHEVRON_RIGHT),
    (Lucide::Copy, "copy", COPY),
    (
        Lucide::EllipsisVertical,
        "ellipsis-vertical",
        ELLIPSIS_VERTICAL,
    ),
    (Lucide::GitBranch, "git-branch", GIT_BRANCH),
    (Lucide::Info, "info", INFO),
    (Lucide::LayoutGrid, "layout-grid", LAYOUT_GRID),
    (Lucide::Menu, "menu", MENU),
    (Lucide::Play, "play", PLAY),
    (Lucide::Plus, "plus", PLUS),
    (Lucide::Blocks, "blocks", BLOCKS),
    (Lucide::Search, "search", SEARCH),
    (Lucide::Settings, "settings", SETTINGS),
    (Lucide::X, "x", X),
    (Lucide::Folder, "folder", FOLDER),
    (Lucide::CornerLeftUp, "corner-left-up", CORNER_LEFT_UP),
    (Lucide::Keyboard, "keyboard", KEYBOARD),
    (Lucide::Diff, "diff", DIFF),
    (Lucide::Bell, "bell", BELL),
    (Lucide::AppWindow, "app-window", APP_WINDOW),
    (Lucide::PanelTop, "panel-top", PANEL_TOP),
    (Lucide::Tag, "tag", TAG),
    (Lucide::Rows3, "rows-3", ROWS3),
    (Lucide::Palette, "palette", PALETTE),
    (Lucide::Terminal, "terminal", TERMINAL),
    (Lucide::Puzzle, "puzzle", PUZZLE),
    (Lucide::Store, "store", STORE),
    (Lucide::Command, "command", COMMAND),
];

/// How many there are.
pub const ICONS: usize = 30;

/// The icons Crook draws, from Lucide.
///
/// Generated: the variants and the geometry come from the same list, so
/// an icon cannot be named without being drawable.
#[derive(Copy, Clone, Debug, Eq, Hash, PartialEq)]
pub enum Lucide {
    /// The mark on a chosen row of the tab options menu and of the settings page.
    ///
    /// Lucide's [`check`](https://lucide.dev/icons/check).
    Check,
    /// An open group's heading in the tabs panel; the find bar's step-to-next-match button.
    ///
    /// Lucide's [`chevron-down`](https://lucide.dev/icons/chevron-down).
    ChevronDown,
    /// The find bar's step-to-previous-match button.
    ///
    /// Lucide's [`chevron-up`](https://lucide.dev/icons/chevron-up).
    ChevronUp,
    /// A folded group's heading, in the same place.
    ///
    /// Lucide's [`chevron-right`](https://lucide.dev/icons/chevron-right).
    ChevronRight,
    /// The control that takes a block's text, on the block the pointer is on.
    ///
    /// Lucide's [`copy`](https://lucide.dev/icons/copy).
    Copy,
    /// The control that opens a block's menu, beside that one.
    ///
    /// Lucide's [`ellipsis-vertical`](https://lucide.dev/icons/ellipsis-vertical).
    EllipsisVertical,
    /// The mark that says a line is a branch and not a path.
    ///
    /// Lucide's [`git-branch`](https://lucide.dev/icons/git-branch).
    GitBranch,
    /// The dot beside a setting that has a note attached.
    ///
    /// Lucide's [`info`](https://lucide.dev/icons/info).
    Info,
    /// The Expanded density, in the tab options menu's segmented control.
    ///
    /// Lucide's [`layout-grid`](https://lucide.dev/icons/layout-grid).
    LayoutGrid,
    /// The Compact density, in the same control. Warp draws `Menu01` here.
    ///
    /// Lucide's [`menu`](https://lucide.dev/icons/menu).
    Menu,
    /// The mark on a control that plays a sound.
    ///
    /// Lucide's [`play`](https://lucide.dev/icons/play).
    Play,
    /// New tab, and new theme.
    ///
    /// Lucide's [`plus`](https://lucide.dev/icons/plus).
    Plus,
    /// The Plugins section, at the foot of the sidebar.
    ///
    /// Lucide's [`blocks`](https://lucide.dev/icons/blocks).
    Blocks,
    /// The settings page's search box, in the rail.
    ///
    /// Lucide's [`search`](https://lucide.dev/icons/search).
    Search,
    /// The mark on a settings row, and on the button that shows one.
    ///
    /// Lucide's [`settings`](https://lucide.dev/icons/settings).
    Settings,
    /// Close: a tab, a panel row, the Themes panel.
    ///
    /// Lucide's [`x`](https://lucide.dev/icons/x).
    X,
    /// A directory: the chip that says where a pane is, and the rows under it.
    ///
    /// Lucide's [`folder`](https://lucide.dev/icons/folder).
    Folder,
    /// The way out of a directory, in a picker that walks one.
    ///
    /// Lucide's [`corner-left-up`](https://lucide.dev/icons/corner-left-up).
    CornerLeftUp,
    /// A chord: what one key would do, on the chip that says so.
    ///
    /// Lucide's [`keyboard`](https://lucide.dev/icons/keyboard).
    Keyboard,
    /// How much has changed in a working tree, on the chip that counts it.
    ///
    /// Lucide's [`diff`](https://lucide.dev/icons/diff).
    Diff,
    /// The tabs that are waiting for you, on the chip in the header that counts them.
    ///
    /// Lucide's [`bell`](https://lucide.dev/icons/bell).
    Bell,
    /// The face of the window's own commands: tabs, panes, splits.
    ///
    /// Lucide's [`app-window`](https://lucide.dev/icons/app-window).
    AppWindow,
    /// The face of the header.
    ///
    /// Lucide's [`panel-top`](https://lucide.dev/icons/panel-top).
    PanelTop,
    /// The face of the pane chips.
    ///
    /// Lucide's [`tag`](https://lucide.dev/icons/tag).
    Tag,
    /// The face of the tabs panel.
    ///
    /// Lucide's [`rows-3`](https://lucide.dev/icons/rows-3).
    Rows3,
    /// The face of the appearance settings.
    ///
    /// Lucide's [`palette`](https://lucide.dev/icons/palette).
    Palette,
    /// The face of the shell settings.
    ///
    /// Lucide's [`terminal`](https://lucide.dev/icons/terminal).
    Terminal,
    /// The face of the Plugins page itself.
    ///
    /// Lucide's [`puzzle`](https://lucide.dev/icons/puzzle).
    Puzzle,
    /// The face of the Store, and its button at the foot of the sidebar.
    ///
    /// Lucide's [`store`](https://lucide.dev/icons/store).
    Store,
    /// The face of the command palette.
    ///
    /// Lucide's [`command`](https://lucide.dev/icons/command).
    Command,
}
