//! The icons themselves: Lucide's geometry, as absolute path commands.
//!
//! Generated by `script/icons` from lucide-static 1.40.0, which is
//! ISC-licensed — see `LICENSE-ISC-lucide`. Do not edit: add an icon to
//! the script's list and run it.
//!
//! Every icon is drawn inside a 24 x 24 box with a 2-unit stroke, round
//! caps and round joins, and no fill. Arcs, shorthands and the `circle`,
//! `rect`, `line` and `polyline` elements are all resolved into moves,
//! lines and cubics here, so the rasterizer needs no SVG in it.

use super::Segment::{self, Close, Cubic, Line, Move};

/// Lucide's `check`.
pub(super) static CHECK: &[Segment] = &[Move(20.0, 6.0), Line(9.0, 17.0), Line(4.0, 12.0)];

/// Lucide's `chevron-down`.
pub(super) static CHEVRON_DOWN: &[Segment] = &[Move(6.0, 9.0), Line(12.0, 15.0), Line(18.0, 9.0)];

/// Lucide's `chevron-right`.
pub(super) static CHEVRON_RIGHT: &[Segment] = &[Move(9.0, 18.0), Line(15.0, 12.0), Line(9.0, 6.0)];

/// Lucide's `copy`.
pub(super) static COPY: &[Segment] = &[
    Move(10.0, 8.0),
    Line(20.0, 8.0),
    Cubic(21.1046, 8.0, 22.0, 8.8954, 22.0, 10.0),
    Line(22.0, 20.0),
    Cubic(22.0, 21.1046, 21.1046, 22.0, 20.0, 22.0),
    Line(10.0, 22.0),
    Cubic(8.8954, 22.0, 8.0, 21.1046, 8.0, 20.0),
    Line(8.0, 10.0),
    Cubic(8.0, 8.8954, 8.8954, 8.0, 10.0, 8.0),
    Close,
    Move(4.0, 16.0),
    Cubic(2.9, 16.0, 2.0, 15.1, 2.0, 14.0),
    Line(2.0, 4.0),
    Cubic(2.0, 2.9, 2.9, 2.0, 4.0, 2.0),
    Line(14.0, 2.0),
    Cubic(15.1, 2.0, 16.0, 2.9, 16.0, 4.0),
];

/// Lucide's `ellipsis-vertical`.
pub(super) static ELLIPSIS_VERTICAL: &[Segment] = &[
    Move(13.0, 12.0),
    Cubic(13.0, 12.5523, 12.5523, 13.0, 12.0, 13.0),
    Cubic(11.4477, 13.0, 11.0, 12.5523, 11.0, 12.0),
    Cubic(11.0, 11.4477, 11.4477, 11.0, 12.0, 11.0),
    Cubic(12.5523, 11.0, 13.0, 11.4477, 13.0, 12.0),
    Close,
    Move(13.0, 5.0),
    Cubic(13.0, 5.5523, 12.5523, 6.0, 12.0, 6.0),
    Cubic(11.4477, 6.0, 11.0, 5.5523, 11.0, 5.0),
    Cubic(11.0, 4.4477, 11.4477, 4.0, 12.0, 4.0),
    Cubic(12.5523, 4.0, 13.0, 4.4477, 13.0, 5.0),
    Close,
    Move(13.0, 19.0),
    Cubic(13.0, 19.5523, 12.5523, 20.0, 12.0, 20.0),
    Cubic(11.4477, 20.0, 11.0, 19.5523, 11.0, 19.0),
    Cubic(11.0, 18.4477, 11.4477, 18.0, 12.0, 18.0),
    Cubic(12.5523, 18.0, 13.0, 18.4477, 13.0, 19.0),
    Close,
];

/// Lucide's `git-branch`.
pub(super) static GIT_BRANCH: &[Segment] = &[
    Move(15.0, 6.0),
    Cubic(10.0627, 6.0, 6.0, 10.0627, 6.0, 15.0),
    Line(6.0, 3.0),
    Move(21.0, 6.0),
    Cubic(21.0, 7.6569, 19.6569, 9.0, 18.0, 9.0),
    Cubic(16.3431, 9.0, 15.0, 7.6569, 15.0, 6.0),
    Cubic(15.0, 4.3431, 16.3431, 3.0, 18.0, 3.0),
    Cubic(19.6569, 3.0, 21.0, 4.3431, 21.0, 6.0),
    Close,
    Move(9.0, 18.0),
    Cubic(9.0, 19.6569, 7.6569, 21.0, 6.0, 21.0),
    Cubic(4.3431, 21.0, 3.0, 19.6569, 3.0, 18.0),
    Cubic(3.0, 16.3431, 4.3431, 15.0, 6.0, 15.0),
    Cubic(7.6569, 15.0, 9.0, 16.3431, 9.0, 18.0),
    Close,
];

/// Lucide's `info`.
pub(super) static INFO: &[Segment] = &[
    Move(22.0, 12.0),
    Cubic(22.0, 17.5228, 17.5228, 22.0, 12.0, 22.0),
    Cubic(6.4772, 22.0, 2.0, 17.5228, 2.0, 12.0),
    Cubic(2.0, 6.4772, 6.4772, 2.0, 12.0, 2.0),
    Cubic(17.5228, 2.0, 22.0, 6.4772, 22.0, 12.0),
    Close,
    Move(12.0, 16.0),
    Line(12.0, 12.0),
    Move(12.0, 8.0),
    Line(12.01, 8.0),
];

/// Lucide's `layout-grid`.
pub(super) static LAYOUT_GRID: &[Segment] = &[
    Move(4.0, 3.0),
    Line(9.0, 3.0),
    Cubic(9.5523, 3.0, 10.0, 3.4477, 10.0, 4.0),
    Line(10.0, 9.0),
    Cubic(10.0, 9.5523, 9.5523, 10.0, 9.0, 10.0),
    Line(4.0, 10.0),
    Cubic(3.4477, 10.0, 3.0, 9.5523, 3.0, 9.0),
    Line(3.0, 4.0),
    Cubic(3.0, 3.4477, 3.4477, 3.0, 4.0, 3.0),
    Close,
    Move(15.0, 3.0),
    Line(20.0, 3.0),
    Cubic(20.5523, 3.0, 21.0, 3.4477, 21.0, 4.0),
    Line(21.0, 9.0),
    Cubic(21.0, 9.5523, 20.5523, 10.0, 20.0, 10.0),
    Line(15.0, 10.0),
    Cubic(14.4477, 10.0, 14.0, 9.5523, 14.0, 9.0),
    Line(14.0, 4.0),
    Cubic(14.0, 3.4477, 14.4477, 3.0, 15.0, 3.0),
    Close,
    Move(15.0, 14.0),
    Line(20.0, 14.0),
    Cubic(20.5523, 14.0, 21.0, 14.4477, 21.0, 15.0),
    Line(21.0, 20.0),
    Cubic(21.0, 20.5523, 20.5523, 21.0, 20.0, 21.0),
    Line(15.0, 21.0),
    Cubic(14.4477, 21.0, 14.0, 20.5523, 14.0, 20.0),
    Line(14.0, 15.0),
    Cubic(14.0, 14.4477, 14.4477, 14.0, 15.0, 14.0),
    Close,
    Move(4.0, 14.0),
    Line(9.0, 14.0),
    Cubic(9.5523, 14.0, 10.0, 14.4477, 10.0, 15.0),
    Line(10.0, 20.0),
    Cubic(10.0, 20.5523, 9.5523, 21.0, 9.0, 21.0),
    Line(4.0, 21.0),
    Cubic(3.4477, 21.0, 3.0, 20.5523, 3.0, 20.0),
    Line(3.0, 15.0),
    Cubic(3.0, 14.4477, 3.4477, 14.0, 4.0, 14.0),
    Close,
];

/// Lucide's `menu`.
pub(super) static MENU: &[Segment] = &[
    Move(4.0, 5.0),
    Line(20.0, 5.0),
    Move(4.0, 12.0),
    Line(20.0, 12.0),
    Move(4.0, 19.0),
    Line(20.0, 19.0),
];

/// Lucide's `play`.
pub(super) static PLAY: &[Segment] = &[
    Move(5.0, 5.0),
    Cubic(4.9998, 4.2846, 5.3834, 3.6216, 6.0038, 3.2652),
    Cubic(6.6241, 2.9088, 7.3901, 2.9114, 8.008, 3.272),
    Line(20.005, 10.27),
    Cubic(20.6204, 10.6271, 21.0006, 11.2867, 21.0012, 11.9981),
    Cubic(21.0019, 12.7096, 20.6228, 13.3699, 20.008, 13.728),
    Line(8.008, 20.728),
    Cubic(7.3901, 21.0886, 6.6241, 21.0912, 6.0038, 20.7348),
    Cubic(5.3834, 20.3784, 4.9998, 19.7154, 5.0, 19.0),
    Close,
];

/// Lucide's `plus`.
pub(super) static PLUS: &[Segment] = &[
    Move(5.0, 12.0),
    Line(19.0, 12.0),
    Move(12.0, 5.0),
    Line(12.0, 19.0),
];

/// Lucide's `blocks`.
pub(super) static BLOCKS: &[Segment] = &[
    Move(10.0, 22.0),
    Line(10.0, 7.0),
    Cubic(10.0, 6.4514, 9.5486, 6.0, 9.0, 6.0),
    Line(4.0, 6.0),
    Cubic(2.9028, 6.0, 2.0, 6.9028, 2.0, 8.0),
    Line(2.0, 20.0),
    Cubic(2.0, 21.0972, 2.9028, 22.0, 4.0, 22.0),
    Line(16.0, 22.0),
    Cubic(17.0972, 22.0, 18.0, 21.0972, 18.0, 20.0),
    Line(18.0, 15.0),
    Cubic(18.0, 14.4514, 17.5486, 14.0, 17.0, 14.0),
    Line(2.0, 14.0),
    Move(15.0, 2.0),
    Line(21.0, 2.0),
    Cubic(21.5523, 2.0, 22.0, 2.4477, 22.0, 3.0),
    Line(22.0, 9.0),
    Cubic(22.0, 9.5523, 21.5523, 10.0, 21.0, 10.0),
    Line(15.0, 10.0),
    Cubic(14.4477, 10.0, 14.0, 9.5523, 14.0, 9.0),
    Line(14.0, 3.0),
    Cubic(14.0, 2.4477, 14.4477, 2.0, 15.0, 2.0),
    Close,
];

/// Lucide's `search`.
pub(super) static SEARCH: &[Segment] = &[
    Move(21.0, 21.0),
    Line(16.66, 16.66),
    Move(19.0, 11.0),
    Cubic(19.0, 15.4183, 15.4183, 19.0, 11.0, 19.0),
    Cubic(6.5817, 19.0, 3.0, 15.4183, 3.0, 11.0),
    Cubic(3.0, 6.5817, 6.5817, 3.0, 11.0, 3.0),
    Cubic(15.4183, 3.0, 19.0, 6.5817, 19.0, 11.0),
    Close,
];

/// Lucide's `settings`.
pub(super) static SETTINGS: &[Segment] = &[
    Move(9.671, 4.136),
    Cubic(9.7846, 2.941, 10.8002, 2.0174, 12.0005, 2.0174),
    Cubic(13.2008, 2.0174, 14.2164, 2.941, 14.33, 4.136),
    Cubic(14.3972, 4.8953, 14.8312, 5.5757, 15.4915, 5.9567),
    Cubic(16.1517, 6.3376, 16.958, 6.3729, 17.649, 6.051),
    Cubic(18.7396, 5.5558, 20.0433, 5.974, 20.6425, 7.0111),
    Cubic(21.2417, 8.0482, 20.9527, 9.3865, 19.979, 10.084),
    Cubic(19.3552, 10.5217, 18.983, 11.2375, 18.983, 11.9995),
    Cubic(18.983, 12.7615, 19.3552, 13.4773, 19.979, 13.915),
    Cubic(20.9527, 14.6125, 21.2417, 15.9508, 20.6425, 16.9879),
    Cubic(20.0433, 18.025, 18.7396, 18.4432, 17.649, 17.948),
    Cubic(16.958, 17.6261, 16.1517, 17.6614, 15.4915, 18.0423),
    Cubic(14.8312, 18.4233, 14.3972, 19.1037, 14.33, 19.863),
    Cubic(14.2164, 21.058, 13.2008, 21.9816, 12.0005, 21.9816),
    Cubic(10.8002, 21.9816, 9.7846, 21.058, 9.671, 19.863),
    Cubic(9.604, 19.1034, 9.1697, 18.4227, 8.5092, 18.0417),
    Cubic(7.8487, 17.6607, 7.0421, 17.6257, 6.351, 17.948),
    Cubic(5.2604, 18.4432, 3.9567, 18.025, 3.3575, 16.9879),
    Cubic(2.7583, 15.9508, 3.0473, 14.6125, 4.021, 13.915),
    Cubic(4.6448, 13.4773, 5.017, 12.7615, 5.017, 11.9995),
    Cubic(5.017, 11.2375, 4.6448, 10.5217, 4.021, 10.084),
    Cubic(3.0487, 9.3862, 2.7605, 8.0491, 3.359, 7.0127),
    Cubic(3.9575, 5.9763, 5.2596, 5.5576, 6.35, 6.051),
    Cubic(7.041, 6.3729, 7.8473, 6.3376, 8.5075, 5.9567),
    Cubic(9.1678, 5.5757, 9.6018, 4.8953, 9.669, 4.136),
    Move(15.0, 12.0),
    Cubic(15.0, 13.6569, 13.6569, 15.0, 12.0, 15.0),
    Cubic(10.3431, 15.0, 9.0, 13.6569, 9.0, 12.0),
    Cubic(9.0, 10.3431, 10.3431, 9.0, 12.0, 9.0),
    Cubic(13.6569, 9.0, 15.0, 10.3431, 15.0, 12.0),
    Close,
];

/// Lucide's `x`.
pub(super) static X: &[Segment] = &[
    Move(18.0, 6.0),
    Line(6.0, 18.0),
    Move(6.0, 6.0),
    Line(18.0, 18.0),
];

/// Lucide's `folder`.
pub(super) static FOLDER: &[Segment] = &[
    Move(20.0, 20.0),
    Cubic(21.0972, 20.0, 22.0, 19.0972, 22.0, 18.0),
    Line(22.0, 8.0),
    Cubic(22.0, 6.9028, 21.0972, 6.0, 20.0, 6.0),
    Line(12.1, 6.0),
    Cubic(11.421, 6.0067, 10.7834, 5.6671, 10.41, 5.1),
    Line(9.6, 3.9),
    Cubic(9.2304, 3.3388, 8.6019, 3.0001, 7.93, 3.0),
    Line(4.0, 3.0),
    Cubic(2.9028, 3.0, 2.0, 3.9028, 2.0, 5.0),
    Line(2.0, 18.0),
    Cubic(2.0, 19.0972, 2.9028, 20.0, 4.0, 20.0),
    Close,
];

/// Lucide's `corner-left-up`.
pub(super) static CORNER_LEFT_UP: &[Segment] = &[
    Move(14.0, 9.0),
    Line(9.0, 4.0),
    Line(4.0, 9.0),
    Move(20.0, 20.0),
    Line(13.0, 20.0),
    Cubic(10.8057, 20.0, 9.0, 18.1943, 9.0, 16.0),
    Line(9.0, 4.0),
];

/// Lucide's `keyboard`.
pub(super) static KEYBOARD: &[Segment] = &[
    Move(10.0, 8.0),
    Line(10.01, 8.0),
    Move(12.0, 12.0),
    Line(12.01, 12.0),
    Move(14.0, 8.0),
    Line(14.01, 8.0),
    Move(16.0, 12.0),
    Line(16.01, 12.0),
    Move(18.0, 8.0),
    Line(18.01, 8.0),
    Move(6.0, 8.0),
    Line(6.01, 8.0),
    Move(7.0, 16.0),
    Line(17.0, 16.0),
    Move(8.0, 12.0),
    Line(8.01, 12.0),
    Move(4.0, 4.0),
    Line(20.0, 4.0),
    Cubic(21.1046, 4.0, 22.0, 4.8954, 22.0, 6.0),
    Line(22.0, 18.0),
    Cubic(22.0, 19.1046, 21.1046, 20.0, 20.0, 20.0),
    Line(4.0, 20.0),
    Cubic(2.8954, 20.0, 2.0, 19.1046, 2.0, 18.0),
    Line(2.0, 6.0),
    Cubic(2.0, 4.8954, 2.8954, 4.0, 4.0, 4.0),
    Close,
];

/// Lucide's `diff`.
pub(super) static DIFF: &[Segment] = &[
    Move(12.0, 3.0),
    Line(12.0, 17.0),
    Move(5.0, 10.0),
    Line(19.0, 10.0),
    Move(5.0, 21.0),
    Line(19.0, 21.0),
];

/// Lucide's `bell`.
pub(super) static BELL: &[Segment] = &[
    Move(10.268, 21.0),
    Cubic(10.6248, 21.618, 11.2864, 21.9999, 12.0, 21.9999),
    Cubic(12.7136, 21.9999, 13.3752, 21.618, 13.732, 21.0),
    Move(3.262, 15.326),
    Cubic(2.9956, 15.618, 2.9263, 16.0417, 3.0857, 16.4034),
    Cubic(3.2452, 16.7651, 3.6047, 16.9997, 4.0, 17.0),
    Line(20.0, 17.0),
    Cubic(20.3952, 17.0001, 20.755, 16.766, 20.9149, 16.4045),
    Cubic(21.0748, 16.0431, 21.006, 15.6193, 20.74, 15.327),
    Cubic(19.41, 13.956, 18.0, 12.499, 18.0, 8.0),
    Cubic(18.0, 4.7085, 15.2915, 2.0, 12.0, 2.0),
    Cubic(8.7085, 2.0, 6.0, 4.7085, 6.0, 8.0),
    Cubic(6.0, 12.499, 4.589, 13.956, 3.262, 15.326),
];

/// Every icon, its Lucide name, and its geometry.
///
/// One table rather than three `match`es, because the three answers are
/// three columns of the same row and a test walks it end to end.
pub(super) static TABLE: [(Lucide, &str, &[Segment]); ICONS] = [
    (Lucide::Check, "check", CHECK),
    (Lucide::ChevronDown, "chevron-down", CHEVRON_DOWN),
    (Lucide::ChevronRight, "chevron-right", CHEVRON_RIGHT),
    (Lucide::Copy, "copy", COPY),
    (
        Lucide::EllipsisVertical,
        "ellipsis-vertical",
        ELLIPSIS_VERTICAL,
    ),
    (Lucide::GitBranch, "git-branch", GIT_BRANCH),
    (Lucide::Info, "info", INFO),
    (Lucide::LayoutGrid, "layout-grid", LAYOUT_GRID),
    (Lucide::Menu, "menu", MENU),
    (Lucide::Play, "play", PLAY),
    (Lucide::Plus, "plus", PLUS),
    (Lucide::Blocks, "blocks", BLOCKS),
    (Lucide::Search, "search", SEARCH),
    (Lucide::Settings, "settings", SETTINGS),
    (Lucide::X, "x", X),
    (Lucide::Folder, "folder", FOLDER),
    (Lucide::CornerLeftUp, "corner-left-up", CORNER_LEFT_UP),
    (Lucide::Keyboard, "keyboard", KEYBOARD),
    (Lucide::Diff, "diff", DIFF),
    (Lucide::Bell, "bell", BELL),
];

/// How many there are.
pub const ICONS: usize = 20;

/// The icons Crook draws, from Lucide.
///
/// Generated: the variants and the geometry come from the same list, so
/// an icon cannot be named without being drawable.
#[derive(Copy, Clone, Debug, Eq, Hash, PartialEq)]
pub enum Lucide {
    /// The mark on a chosen row of the tab options menu and of the settings page.
    ///
    /// Lucide's [`check`](https://lucide.dev/icons/check).
    Check,
    /// An open group's heading in the tabs panel: click to fold it away.
    ///
    /// Lucide's [`chevron-down`](https://lucide.dev/icons/chevron-down).
    ChevronDown,
    /// A folded group's heading, in the same place.
    ///
    /// Lucide's [`chevron-right`](https://lucide.dev/icons/chevron-right).
    ChevronRight,
    /// The control that takes a block's text, on the block the pointer is on.
    ///
    /// Lucide's [`copy`](https://lucide.dev/icons/copy).
    Copy,
    /// The control that opens a block's menu, beside that one.
    ///
    /// Lucide's [`ellipsis-vertical`](https://lucide.dev/icons/ellipsis-vertical).
    EllipsisVertical,
    /// The mark that says a line is a branch and not a path.
    ///
    /// Lucide's [`git-branch`](https://lucide.dev/icons/git-branch).
    GitBranch,
    /// The dot beside a setting that has a note attached.
    ///
    /// Lucide's [`info`](https://lucide.dev/icons/info).
    Info,
    /// The Expanded density, in the tab options menu's segmented control.
    ///
    /// Lucide's [`layout-grid`](https://lucide.dev/icons/layout-grid).
    LayoutGrid,
    /// The Compact density, in the same control. Warp draws `Menu01` here.
    ///
    /// Lucide's [`menu`](https://lucide.dev/icons/menu).
    Menu,
    /// The mark on a control that plays a sound.
    ///
    /// Lucide's [`play`](https://lucide.dev/icons/play).
    Play,
    /// New tab, and new theme.
    ///
    /// Lucide's [`plus`](https://lucide.dev/icons/plus).
    Plus,
    /// The Plugins section, at the foot of the sidebar.
    ///
    /// Lucide's [`blocks`](https://lucide.dev/icons/blocks).
    Blocks,
    /// The settings page's search box, in the rail.
    ///
    /// Lucide's [`search`](https://lucide.dev/icons/search).
    Search,
    /// The mark on a settings row, and on the button that shows one.
    ///
    /// Lucide's [`settings`](https://lucide.dev/icons/settings).
    Settings,
    /// Close: a tab, a panel row, the Themes panel.
    ///
    /// Lucide's [`x`](https://lucide.dev/icons/x).
    X,
    /// A directory: the chip that says where a pane is, and the rows under it.
    ///
    /// Lucide's [`folder`](https://lucide.dev/icons/folder).
    Folder,
    /// The way out of a directory, in a picker that walks one.
    ///
    /// Lucide's [`corner-left-up`](https://lucide.dev/icons/corner-left-up).
    CornerLeftUp,
    /// A chord: what one key would do, on the chip that says so.
    ///
    /// Lucide's [`keyboard`](https://lucide.dev/icons/keyboard).
    Keyboard,
    /// How much has changed in a working tree, on the chip that counts it.
    ///
    /// Lucide's [`diff`](https://lucide.dev/icons/diff).
    Diff,
    /// The tabs that are waiting for you, on the chip in the header that counts them.
    ///
    /// Lucide's [`bell`](https://lucide.dev/icons/bell).
    Bell,
}
